import type { Project } from "./types.ts";

export const projects: Project[] = [
  {
    id: "proj-robotwin2",
    title: "RoboTwin 2.0",
    context: "ICML 2026",
    category: "Simulation · Bimanual",
    dates: { start: "2025.04", end: "2025.07" },
    status: "evidenced",
    researchQuestion:
      "How can we generate large, diverse synthetic data that makes bimanual manipulation policies robust enough to transfer to the real world?",
    summary:
      "A simulation framework that automatically generates large-scale, diverse synthetic data for dual-arm manipulation, combining multimodal large language models with five-dimensional domain randomization.",
    outcome: "Improved policy robustness and sim-to-real transfer, with large gains from only a small amount of real data.",
    resultScope: "team",
    highlight: "Best Paper · IROS 2025 RoDGE Workshop",
    tools: ["Simulation", "Domain Randomization", "Bimanual Manipulation"],
    role: "Co-author",
    roleConfirmed: false,
    topics: ["robot-learning", "sim2real"],
    links: [],
    glyph: "sim2real",
    schematic: "sim2real",
    featured: true,
    size: "feature",
    evidence: ["PUB-ROBOTWIN2", "EXP-AGILEX"],
    order: 1,
  },
  {
    id: "proj-dexhand-xjgn",
    title: "Dexterous hand control, early-generation product",
    context: "R&D Intern · Shenzhen Xingji Guangnian Technology",
    category: "Hardware · Control",
    dates: { start: "2024.09", end: "2025.01" },
    status: "evidenced",
    researchQuestion:
      "What control architecture lets an early-stage dexterous hand move from prototype hardware to a reliable, demonstrable manipulator?",
    summary:
      "Built the hand’s control framework on embedded hardware and software, and designed its control and demo algorithms.",
    outcome:
      "The product was selected for HK DeepTech100 and the Google Cloud startup program, and won 1st prize at XbotMan-2024.",
    resultScope: "product",
    tools: ["Dexterous Hands", "Embedded Control"],
    role: "R&D Intern: control framework and algorithms",
    roleConfirmed: true,
    topics: ["dexterous-manipulation"],
    links: [],
    glyph: "hand",
    schematic: "dexhand",
    size: "standard",
    evidence: ["EXP-XJGN"],
    order: 2,
  },
  {
    id: "proj-mmhand",
    title: "MM-Hand 1.0",
    context: "Design Consultant · Shenzhen Hetao Institute × HKU MMLab",
    category: "Hardware · Mechanism",
    dates: { start: "2025.08", end: "2026.05" },
    status: "evidenced",
    researchQuestion:
      "How should a research dexterous hand be designed mechanically and in control logic so it’s dependable for lab manipulation research?",
    summary:
      "Proposed mechanical structure concepts (widely adopted), debugged embedded software, and designed the control algorithms and state machine.",
    outcome: "MM-Hand 1.0 delivered.",
    tools: ["Dexterous Hands", "Mechanical Design", "State Machines"],
    role: "Design Consultant",
    roleConfirmed: true,
    topics: ["dexterous-manipulation"],
    links: [],
    glyph: "hand",
    schematic: "mmhand",
    size: "standard",
    evidence: ["EXP-MMHAND"],
    order: 3,
  },
  {
    id: "proj-g3flow",
    title: "G3Flow",
    context: "CVPR 2025",
    category: "Perception · Manipulation",
    dates: { start: "2024.08", end: "2024.11" },
    status: "evidenced",
    researchQuestion:
      "How can a robot keep an up-to-date, pose-aware semantic understanding of objects to generalize manipulation without manual annotation?",
    summary:
      "A dynamic 3D semantic flow built from 3D generative models, vision foundation models, and robust pose tracking, updating semantic features in real time without manual annotation.",
    tools: ["3D Vision", "Computer Vision"],
    role: "Co-author",
    roleConfirmed: false,
    topics: ["robot-learning"],
    links: [],
    glyph: "flow3d",
    schematic: "flow3d",
    size: "standard",
    evidence: ["PUB-G3FLOW"],
    order: 4,
  },
  {
    id: "proj-mars",
    title: "MARS 2025 Challenge (SpaVLE), Track 2",
    context: "NeurIPS 2025 · Simulation data and policy tuning",
    category: "Simulation · Policy",
    dates: { start: "2025.09", end: "2025.11" },
    status: "evidenced",
    researchQuestion:
      "What data and policy configuration choices most improve embodied task success in simulation?",
    summary:
      "Collected simulation data, ran validation experiments, and tuned policy configurations to raise task success rate.",
    resultScope: "team",
    highlight: "Champion · Track 2",
    tools: ["Simulation", "Policy Evaluation"],
    role: "Team member: simulation data and policy tuning",
    roleConfirmed: true,
    topics: ["robot-learning", "sim2real"],
    links: [],
    glyph: "policy",
    schematic: "policy",
    size: "standard",
    evidence: ["CHL-MARS"],
    order: 5,
  },
  {
    id: "proj-capro",
    title: "CaPro",
    context: "AAAI 2026 · Poster · Co-first author",
    category: "Perception · Segmentation",
    dates: { start: "2024.07", end: "2025.03" },
    status: "evidenced",
    researchQuestion:
      "Can a segmentation foundation model be adapted to thin, curvilinear structures using just one unlabeled image?",
    summary:
      "Adapts the Segment Anything Model to curvilinear structures from a single unlabeled image, with automatically generated and refined visual prompts.",
    outcome: "Strong performance on medical and crack segmentation tasks.",
    tools: ["Segmentation", "Foundation Models (SAM)"],
    role: "Co-first author",
    roleConfirmed: true,
    topics: [],
    links: [],
    glyph: "segment",
    schematic: "segment",
    size: "compact",
    evidence: ["PUB-CAPRO"],
    order: 6,
  },
];
