import type { WritingContent } from "./types.ts";

export const writing: WritingContent = {
  papers: [
    {
      id: "pub-robotwin2",
      kind: "paper",
      shortTitle: "RoboTwin 2.0",
      title:
        "A Scalable Data Generator and Benchmark with Strong Domain Randomization for Robust Bimanual Robotic Manipulation",
      venue: "ICML",
      domain: "Robotics",
      year: 2026,
      honors: [
        "Best Paper, RoDGE Workshop @ IROS 2025",
        "Excellent Poster, China Spatial Intelligence Conference",
      ],
      highlight: "Best Paper",
      publishedAs: "Qiangyu Chen",
      links: [],
      relatedProject: "proj-robotwin2",
      evidence: ["PUB-ROBOTWIN2"],
    },
    {
      id: "pub-capro",
      kind: "paper",
      shortTitle: "CaPro",
      title:
        "Curvilinear-aware Prompt Learning with Single Unlabeled Image for Cost-effective Curvilinear Structure Segmentation",
      venue: "AAAI",
      format: "poster",
      domain: "Vision",
      year: 2026,
      authorNote: "Co-first author",
      publishedAs: "Qiangyu Chen",
      links: [],
      relatedProject: "proj-capro",
      evidence: ["PUB-CAPRO"],
    },
    {
      id: "pub-g3flow",
      kind: "paper",
      shortTitle: "G3Flow",
      title: "Generative 3D Semantic Flow for Pose-aware and Generalizable Object Manipulation",
      venue: "CVPR",
      domain: "Robotics",
      year: 2025,
      publishedAs: "Qiangyu Chen",
      links: [],
      relatedProject: "proj-g3flow",
      evidence: ["PUB-G3FLOW"],
    },
    {
      id: "pub-aicl",
      kind: "paper",
      title: "Attack-inspired Calibration Loss for Calibrating Crack Recognition",
      venue: "AAAI",
      format: "poster",
      domain: "Vision",
      year: 2025,
      authorNote: "Second author",
      publishedAs: "Qiangyu Chen",
      links: [],
      evidence: ["PUB-AICL"],
    },
  ],
  recognition: [
    {
      id: "rec-mars",
      kind: "recognition",
      title: "Champion, MARS 2025 Challenge (SpaVLE) Track 2 @ NeurIPS 2025",
      year: 2025,
      publishedAs: "Qiangyu Chen",
      links: [],
      relatedProject: "proj-mars",
      evidence: ["CHL-MARS"],
    },
    {
      id: "rec-mera",
      kind: "recognition",
      title: "Outstanding Research Project Award 2026, City University of Hong Kong",
      summary: "Data-Dependent Thresholds and Structured Non-Monotonicity in Low-Rank MERA Image Fitting",
      year: 2026,
      publishedAs: "Qiangyu Chen",
      links: [],
      evidence: ["RES-MERA", "EDU-CITYU-AWD"],
    },
  ],
  notes: [],
  notesEmptyCopy: {
    title: "Research notes: forthcoming.",
    body: "Short write-ups on dexterous hand control, simulation data generation, and sim-to-real will appear here.",
  },
};
