import type { Project } from "./types.ts";
import {
  aiclReliability,
  caproIntro,
  chinasiCertificate,
  g3flowTeaser,
  irosCertificate,
  marsCertificateCover,
  mmhandOverview,
  robotwinTeaser,
} from "./figures.ts";

export const projects: Project[] = [
  {
    id: "proj-robotwin2",
    title: "RoboTwin 2.0",
    context: "ICML 2026",
    category: "Simulation · Bimanual",
    dates: { start: "2025.04", end: "2025.07" },
    status: "evidenced",
    summary:
      "A simulation framework that automatically generates large-scale, diverse synthetic data for dual-arm manipulation, combining multimodal large language models with five-dimensional domain randomization.",
    outcome: "Improved policy robustness and sim-to-real transfer, with large gains from only a small amount of real data.",
    resultScope: "team",
    highlight: "Best Poster · IROS 2025 RoDGE Workshop",
    tools: ["Simulation", "Domain Randomization", "Bimanual Manipulation"],
    links: [
      { kind: "site", label: "Project", href: "https://robotwin-platform.github.io/" },
      { kind: "paper", label: "arXiv", href: "https://arxiv.org/abs/2506.18088" },
    ],
    media: robotwinTeaser,
    awards: [irosCertificate, chinasiCertificate],
    evidence: ["PUB-ROBOTWIN2", "EXP-AGILEX"],
    order: 1,
  },
  {
    id: "proj-mmhand",
    title: "MM-Hand 1.0",
    context: "Design Consultant · Shenzhen Hetao Institute × HKU MMLab",
    category: "Hardware · Mechanism",
    dates: { start: "2025.08", end: "2026.05" },
    status: "evidenced",
    summary:
      "Proposed mechanical structure concepts (widely adopted), debugged embedded software, and designed the control algorithms and state machine.",
    outcome: "MM-Hand 1.0 delivered.",
    tools: ["Dexterous Hands", "Mechanical Design", "State Machines"],
    links: [{ kind: "paper", label: "arXiv", href: "https://arxiv.org/abs/2604.17245" }],
    media: mmhandOverview,
    evidence: ["EXP-MMHAND"],
    order: 3,
  },
  {
    id: "proj-g3flow",
    title: "G3Flow",
    context: "CVPR 2025",
    category: "Perception · Manipulation",
    dates: { start: "2024.08", end: "2024.11" },
    status: "evidenced",
    summary:
      "A dynamic 3D semantic flow built from 3D generative models, vision foundation models, and robust pose tracking, updating semantic features in real time without manual annotation.",
    tools: ["3D Vision", "Computer Vision"],
    links: [
      { kind: "site", label: "Project", href: "https://tianxingchen.github.io/G3Flow/" },
      { kind: "paper", label: "arXiv", href: "https://arxiv.org/abs/2411.18369" },
    ],
    media: g3flowTeaser,
    evidence: ["PUB-G3FLOW"],
    order: 4,
  },
  {
    id: "proj-mars",
    title: "MARS 2025 Challenge (SpaVLE), Control Track",
    context: "NeurIPS 2025 · Simulation data and policy tuning",
    category: "Simulation · Policy",
    dates: { start: "2025.09", end: "2025.11" },
    status: "evidenced",
    summary:
      "Collected simulation data, ran validation experiments, and tuned policy configurations to raise task success rate.",
    resultScope: "team",
    highlight: "Champion · Control Track",
    tools: ["Simulation", "Policy Evaluation"],
    links: [
      { kind: "site", label: "Challenge", href: "https://mars-eai.github.io/MARS-Challenge-Webpage/" },
      { kind: "paper", label: "Report", href: "https://arxiv.org/abs/2601.18733" },
    ],
    media: marsCertificateCover,
    evidence: ["CHL-MARS"],
    order: 5,
  },
  {
    id: "proj-capro",
    title: "CaPro",
    context: "AAAI 2026 · Poster · Co-first author",
    category: "Perception · Segmentation",
    dates: { start: "2024.07", end: "2025.03" },
    status: "evidenced",
    summary:
      "Adapts the Segment Anything Model to curvilinear structures from a single unlabeled image, with automatically generated and refined visual prompts.",
    outcome: "Strong performance on medical and crack segmentation tasks.",
    tools: ["Segmentation", "Foundation Models (SAM)"],
    links: [
      { kind: "paper", label: "AAAI", href: "https://ojs.aaai.org/index.php/AAAI/article/view/37315" },
      { kind: "code", label: "Code", href: "https://github.com/xmed-lab/CaPro" },
    ],
    media: caproIntro,
    evidence: ["PUB-CAPRO"],
    order: 6,
  },
  {
    id: "proj-aicl",
    title: "Attack-inspired Calibration Loss",
    context: "AAAI 2025 · Poster · Second author",
    category: "Perception · Recognition",
    dates: {},
    status: "evidenced",
    summary:
      "A plug-and-play loss that estimates how likely each crack prediction is to be correct from the number of adversarial attack rounds needed to flip it, then aligns the model’s confidence with that estimate.",
    outcome: "Outperforms prior calibration methods on CRACK2019, SDNET2018, and the new BRIDGE2024 dataset.",
    tools: ["Computer Vision", "Calibration"],
    links: [
      { kind: "paper", label: "AAAI", href: "https://ojs.aaai.org/index.php/AAAI/article/view/33755" },
      { kind: "code", label: "Dataset", href: "https://github.com/cheny124800/AICL" },
    ],
    media: aiclReliability,
    evidence: ["PUB-AICL"],
    order: 7,
  },
];
